# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/octoprint/all/octoprint.rbi
#
# octoprint-0.1.0

module Octoprint
end
class Octoprint::ServerVersion < Octoprint::BaseResource
  def api; end
  def initialize(api:, server:, text:); end
  def self.get; end
  def server; end
  def text; end
end
