inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'sorbet/rbi/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# Allow higher complexity for infrastructure/metaprogramming methods
Metrics/AbcSize:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'
    - 'lib/tapioca/dsl/compilers/auto_initializable.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'
    - 'lib/tapioca/dsl/compilers/auto_initializable.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'
    - 'lib/tapioca/dsl/compilers/auto_initializable.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'
    - 'lib/tapioca/dsl/compilers/auto_initializable.rb'

# Disable DocumentDynamicEvalDefinition for metaprogramming modules
Style/DocumentDynamicEvalDefinition:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'

# Allow more flexible RSpec rules for comprehensive testing
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 45

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - integration

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - 'spec/integration/**/*'


# Allow constant definition in test blocks for test-specific classes
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

plugins:
  - rubocop-rspec
