inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'sorbet/rbi/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# Allow higher complexity for infrastructure/metaprogramming methods
Metrics/AbcSize:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'

# Disable DocumentDynamicEvalDefinition for metaprogramming modules
Style/DocumentDynamicEvalDefinition:
  Exclude:
    - 'lib/octoprint/auto_initializable.rb'
    - 'lib/octoprint/deserializable.rb'

plugins:
  - rubocop-rspec
