# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Connection`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Connection`.

class Octoprint::Connection
  sig { returns(T.nilable(::Octoprint::Connection::Settings)) }
  def current; end

  sig { returns(T.nilable(::Octoprint::Connection::Options)) }
  def options; end
end
