# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Job`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Job`.


class Octoprint::Job
  sig { returns(T.nilable(::String)) }
  def error; end

  sig { returns(T.nilable(::Octoprint::Job::Information)) }
  def information; end

  sig { returns(T.nilable(::Octoprint::Job::Progress)) }
  def progress; end

  sig { returns(T.nilable(::String)) }
  def state; end
end
