# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Languages`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Languages`.


class Octoprint::Languages
  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(::Hash) }
  def language_packs; end
end
