# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Logs`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Logs`.


class Octoprint::Logs
  sig { returns(T::Array[::Octoprint::Logs::LogFile]) }
  def files; end

  sig { returns(T.nilable(::Integer)) }
  def free; end
end
