# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::PrinterProfiles`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::PrinterProfiles`.


class Octoprint::PrinterProfiles
  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(::Hash) }
  def profiles; end
end
