# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::ServerInformation`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::ServerInformation`.


class Octoprint::ServerInformation
  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(T.nilable(::String)) }
  def safemode; end

  sig { returns(::String) }
  def version; end
end
