# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::ServerVersion`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::ServerVersion`.


class Octoprint::ServerVersion
  sig { returns(::String) }
  def api; end

  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(::String) }
  def server; end

  sig { returns(::String) }
  def text; end
end
