# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::SystemCommands`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::SystemCommands`.


class Octoprint::SystemCommands
  sig { returns(T::Array[::Octoprint::SystemCommands::Command]) }
  def core; end

  sig { returns(T::Array[::Octoprint::SystemCommands::Command]) }
  def custom; end

  sig { returns(T.nilable(::Hash)) }
  def extra; end
end
