# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::User`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::User`.


class Octoprint::User
  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(T.nilable(::Array)) }
  def groups; end

  sig { returns(::String) }
  def name; end

  sig { returns(T.nilable(::Array)) }
  def permissions; end
end
