# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Util`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Util`.


class Octoprint::Util
  sig { returns(T.nilable(T::Boolean)) }
  def exists; end

  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(T.nilable(::String)) }
  def result; end

  sig { returns(T.nilable(::String)) }
  def status; end
end
