# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Files::Refs`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Files::Refs`.

class Octoprint::Files::Refs
  sig { returns(T.nilable(::String)) }
  def download; end

  sig { returns(T.nilable(::String)) }
  def model; end

  sig { returns(T.nilable(::String)) }
  def resource; end
end
