# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Languages::LanguagePackList`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Languages::LanguagePackList`.


class Octoprint::Languages::LanguagePackList
  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(T::Array[::Octoprint::Languages::LanguagePack]) }
  def language_packs; end
end
