# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Languages::LanguagePack`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Languages::LanguagePack`.


class Octoprint::Languages::LanguagePack
  sig { returns(::String) }
  def display; end

  sig { returns(T.nilable(::Hash)) }
  def extra; end

  sig { returns(::String) }
  def identifier; end

  sig { returns(::Array) }
  def languages; end
end
