# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Logs::LogFile`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Logs::LogFile`.


class Octoprint::Logs::LogFile
  sig { returns(::Integer) }
  def date; end

  sig { returns(::String) }
  def name; end

  sig { returns(T.nilable(::Octoprint::Logs::References)) }
  def refs; end

  sig { returns(::Integer) }
  def size; end
end
