# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Octoprint::Logs::References`.
# Please instead update this file by running `bin/tapioca dsl Octoprint::Logs::References`.


class Octoprint::Logs::References
  sig { returns(T.nilable(::String)) }
  def download; end

  sig { returns(T.nilable(::String)) }
  def resource; end
end
