name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest


##
# Ruby 3.3
# status: preview
# release date:
# normal maintenance until: TBD
# EOL: TBD

# Ruby 3.2
# status: normal maintenance
# release date: 2022-12-25
# normal maintenance until: TBD
# EOL: 2026-03-31 (expected)

# Ruby 3.1
# status: normal maintenance
# release date: 2021-12-25
# normal maintenance until: TBD
# EOL: 2025-03-31 (expected)

# Ruby 3.0
# status: security maintenance
# release date: 2020-12-25
# normal maintenance until: 2023-04-01
# EOL: 2024-03-31 (expected)


    strategy:
      matrix:
        ruby:
          - 3.0.0
          - 3.0.1
          - 3.0.2
          - 3.0.3
          - 3.0.4
          - 3.0.5
          - 3.0.6
          - 3.1.0
          - 3.1.1
          - 3.1.2
          - 3.1.3
          - 3.1.4
          - 3.2.0
          - 3.2.1
          - 3.2.2
          - 3.3.0-preview1

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
